development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  # url: <%= ENV['REDISCLOUD_URL'] %>
  url: <%= ENV.fetch("REDISCLOUD_URL") %>/<%= ENV.fetch("REDISCLOUD_DB") %>
  # url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/0" } %>
  channel_prefix: art--collabs_production
