development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  # url: <%= ENV.fetch('REDISCLOUD_URL') %>
  # url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://default:HTrniZMBJPSngtCxV5vDzz58Dp4qKBK4@redis-13674.c77.eu-west-1-1.ec2.cloud.redislabs.com:13674" } %>
  channel_prefix: art--collabs_production
