development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  # url: <%= ENV.fetch('REDISCLOUD_URL') %>
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://redistogo:f21476d60ea30dc18e278639f2cf2493@soapfish.redistogo.com:11323/" } %>
  # url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: art--collabs_production
