meta_product_name: "ARTCOLLABs"
meta_title: "ARTCOLLABs: Let's make things happen."
meta_description: "We are here to help you find your next creative team!"
meta_image: "cover.png" # should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"   # required for Twitter Cards
